version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  static_volume:
